---
- hosts: localhost
  connection: local
  
  vars:
    docker_edition: 'ce'
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    anaconda_python_ver : 3
    anaconda_ver: '5.1.0'
  
  roles:
    - role: ansible-role-docker
    - role: ansible-anaconda

  tasks:
    - name: Install pip2
      apt: name_{{ item }}
      with_items:
        - python-pip
      install_recommends: True
      become: yes
      update_cache: True

    - name: Install Python packages
      pip: name={{ item }}
      with_items:
        - docker
      become: yes

    - name: run Shiny container
      docker_container:
        name: shiny
        image: rocker\shiny
        state: started
        pull: no            #Always pull latest version
        ports:
          - "3838:3838"
        volumes:
          - "/srv/shinyapps/:/srv/shiny-server/"
          - "/srv/shinylog/:/var/log/shiny-server/"
