---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Load Requirements
      local_action: command ansible-galaxy install -r  ./roles/requirements.yml

  vars:
    docker_edition: 'ce'
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
  
  roles:
    - role: ansible-role-docker

  tasks:
    # - name: pull Shiny container
    #   docker_image: 
    #     name: rocker\shiny
    #     state: present
    - name: Install Python packages
      pip: name={{ item }}
      with_items:
        - docker
      become: yes

    - name: run Shiny container
      docker_container:
        name: shiny
        image: rocker\shiny
        state: started
        pull: no            #Always pull latest version
        ports:
          - "3838:3838"
        volumes:
          - "/srv/shinyapps/:/srv/shiny-server/"
          - "/srv/shinylog/:/var/log/shiny-server/"