---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Load Requirements
      local_action: command ansible-galaxy install -r  ./roles/requirements.yml

  vars:
    docker_edition: 'ce'
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
  
#   roles:
#     - role: ansible-role-docker
    
