---
- hosts: localhost
  connection: local

  pre_tasks:
    - file:
      path: roles
      state: absent
    
    - local_action: command ansible-galaxy install -r requirements.yml

  vars:
    docker_edition: 'ce'
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
  
  roles:
    - role: ansible-role-docker
    